/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/features` | `/features`; params?: Router.UnknownInputParams; } | { pathname: `/detail-analysis`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownInputParams; } | { pathname: `/add-document`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/search/[method]`, params: Router.UnknownInputParams & { method: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/features` | `/features`; params?: Router.UnknownOutputParams; } | { pathname: `/detail-analysis`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownOutputParams; } | { pathname: `/add-document`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/search/[method]`, params: Router.UnknownOutputParams & { method: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/features${`?${string}` | `#${string}` | ''}` | `/features${`?${string}` | `#${string}` | ''}` | `/detail-analysis${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/guide${`?${string}` | `#${string}` | ''}` | `/guide${`?${string}` | `#${string}` | ''}` | `/add-document${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/features` | `/features`; params?: Router.UnknownInputParams; } | { pathname: `/detail-analysis`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownInputParams; } | { pathname: `/add-document`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/search/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/search/[method]`, params: Router.UnknownInputParams & { method: string | number; } };
    }
  }
}
